version: "3"
services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    ports:
      - 9101
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - 3000
    restart: unless-stopped
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - monitoring
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.grafana-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.grafana-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.grafana-web.middlewares=grafana-redirect-websecure"
      - traefik.http.routers.grafana-web.rule=Host(`grafana.thexiao77.com`)
      - traefik.http.routers.grafana-web.entrypoints=http
      - traefik.http.routers.grafana-websecure.rule=Host(`grafana.thexiao77.com`)
      - traefik.http.routers.grafana-websecure.tls.certresolver=le
      - traefik.http.routers.grafana-websecure.tls=true
      - traefik.http.routers.grafana-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
  cadvisor:
    image: zcube/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

networks:
  monitoring:
    external: true
  proxy:
    external: true
